### ISSUE TITLE
Card data missing

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/aries-mobileagent-iOS#51]
Some cards existed from before.:  used new connection QR code’s generated on-demand. The card data doesn’t get populated.

Please see the attached video. For the second instance of the travel company it hangs.

**Comment by lalc** [comment]
https://user-images.githubusercontent.com/455274/106366288-1ca92700-633b-11eb-863f-3b64b0dbc752.MP4

**Comment by darkchylde** [comment]
@lalc It's not issue in the backend FYI. @rebink Could you check this ?

**Comment by lalc** [comment]
got it. Thanks @darkchylde 

I do feel we need to figure out a way to "stack" connections that belongs to the same company. Otherwise, imagine accumulating 100s of logos. :)

**Comment by darkchylde** [comment]
For iGrant.io agents it should be possible.

**Comment by rebink** [comment]
@darkchylde @lalc The old Travel Company org will not work, Since it is deleted from the server. And new Travel Company org is getting some error as mentioned below.


**protocol :** "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/igrantio-operator/1.0/organization-info",

**Response :** ["message": {"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/igrantio-operator/1.0/problem_report", "@id": "50f38a06-935c-4ad4-9a69-fe0da396e4e3", "problem-code": "operator_not_configured", "explain": "Operator is not configured or invalid configuration provided."}, "sender_verkey": CwVDj9rvsSCCL41HV6b77AyfwAc6mVcd9JktAa6Jj86L, "recipient_verkey": H12BUARc5MReENyS8jEbNj4M8WE3qCRxfYuNCdwqYcuL]

**Comment by rebink** [comment]
@darkchylde When new Travel company QR code is scanning , I'm getting statuscode 504 for protocol type - "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/request",

**Comment by darkchylde** [comment]
Will check this

**Comment by darkchylde** [comment]
Resolved this. iGrant.io operator protocol was not configured.
